apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: task-events-sub
spec:
  pubsubname: pubsub-kafka
  topic: task-events
  routes:
    default: /events/task
  scopes:
    - recurring-service
