openapi: 3.0.3
info:
  title: TaskFlow Backend API
  description: |
    REST API for TaskFlow multi-user task management application.
    All endpoints require JWT authentication via Better Auth.
  version: 1.0.0
  contact:
    name: TaskFlow Team

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.taskflow.example.com
    description: Production server

security:
  - BearerAuth: []

paths:
  /api/{user_id}/tasks:
    get:
      summary: List all tasks for user
      operationId: getTasks
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

    post:
      summary: Create a new task
      operationId: createTask
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskDTO'
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '422':
          $ref: '#/components/responses/ValidationError'

  /api/{user_id}/tasks/{task_id}:
    get:
      summary: Get a single task
      operationId: getTask
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/TaskId'
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Update a task
      operationId: updateTask
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/TaskId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskDTO'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'

    delete:
      summary: Delete a task
      operationId: deleteTask
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/TaskId'
      responses:
        '204':
          description: Task deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from Better Auth

  parameters:
    UserId:
      name: user_id
      in: path
      required: true
      description: User ID (must match JWT sub claim)
      schema:
        type: string
        example: user_abc123

    TaskId:
      name: task_id
      in: path
      required: true
      description: Task ID
      schema:
        type: integer
        example: 1

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - is_completed
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Unique task identifier
          example: 1
        user_id:
          type: string
          description: Owner user ID
          example: user_abc123
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title
          example: Buy groceries
        description:
          type: string
          nullable: true
          description: Task description (optional)
          example: Milk, eggs, bread
        is_completed:
          type: boolean
          description: Completion status
          example: false
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
          example: "2026-01-05T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2026-01-05T10:30:00Z"

    CreateTaskDTO:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title (required)
          example: Buy groceries
        description:
          type: string
          nullable: true
          description: Task description (optional)
          example: Milk, eggs, bread

    UpdateTaskDTO:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: New task title
          example: Updated title
        description:
          type: string
          nullable: true
          description: New task description
          example: Updated description
        is_completed:
          type: boolean
          description: New completion status
          example: true

    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Human-readable error message
          example: Task not found

  responses:
    Unauthorized:
      description: Authentication required or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            missing:
              summary: No token provided
              value:
                detail: Invalid authorization header
            invalid:
              summary: Invalid token
              value:
                detail: Invalid token
            expired:
              summary: Token expired
              value:
                detail: Token expired

    Forbidden:
      description: Access denied (user ID mismatch)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: Forbidden

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: Task not found

    ValidationError:
      description: Request validation failed
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: array
                items:
                  type: object
                  properties:
                    loc:
                      type: array
                      items:
                        type: string
                    msg:
                      type: string
                    type:
                      type: string
          example:
            detail:
              - loc: ["body", "title"]
                msg: "String should have at least 1 character"
                type: "string_too_short"

tags:
  - name: Tasks
    description: Task CRUD operations
